#!/bin/bash

NORM=`tput sgr0`
BOLD=`tput bold`
RED=$(tput setaf 1)
WHITE=$(tput setaf 7)
GREEN=$(tput setaf 2)
BLACK=$(tput setaf 0)
GREENBG=$(tput setab 2)
BLACKBG=$(tput setab 0)

if [ $# == 0 ]; then
    echo "no project name was passed, which can possibly delete the entire source folder"
    echo "what in the hell are you doing?"
    exit 1
fi

PROJECT_NAME=$1

if [ -d "src/${PROJECT_NAME}" ]; then
    while true; do
        read -p "Are you sure you want to delete ${PROJECT_NAME}?" yn
        case $yn in
            [Yy]* ) 
                rm -rf ./src/$PROJECT_NAME
                echo -e "${GREEN}\"${PROJECT_NAME}\" has been removed"
                exit 0
                ;;
            [Nn]* )
                exit 0
                ;;
            * )
                echo -e "Please answer yes or no"
                ;;
        esac
    done
else
    echo -e "${RED}\"${PROJECT_NAME}\" does not exist"
    exit 0
fi